apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus
resources:
  - nexus-namespace.yaml
  - nexus-deployment.yaml
  - nexus-ingress.yaml
  - nexus-pvc.yaml
  - nexus-svc.yaml