apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/grafana-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: grafana-operator