apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nexus
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/nexus
  prune: true
  dependsOn:
    - name: local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: nexus