# manifests/cluster/flux-system/postgres.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
