---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  interval: 10m0s
  provider: generic
  ref:
    tag: v5.6.3
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-operator
spec:
  interval: 5m0s
  chartRef:
    kind: OCIRepository
    name: grafana-operator
    namespace: grafana-operator
  values: {}